/*Autogenerated data file */
#include "htmlfiles.h"

const char * default_page="INDEX.HTM";

const unsigned char FilePointer0[]={
156, 62, 13, 10,138, 62, 13, 10,  0,  1,  0,  1, 32, 32, 13,
 10,202, 62, 13, 10,220, 62, 13, 10,255,};


extern const char * MIME_table[1];

extern const HTML_FILE_RECORD file_record[1];

extern const unsigned  n_file_record;

const unsigned  n_file_record=1;

const char * MIME_table[1]={
"text/html",
};


const HTML_FILE_RECORD file_record[1]={
{"index.htm",FilePointer0,25,eHuffmanHtml,0, 1},
}; 


const int file_password_groups[2]={
0,-1}; 

extern const char *  html_table[];
const char *  html_table[64]={
"A","ADDRESS","APPLET","AREA",
"B","BASE","BASEFONT","BIG",
"BLINK","BLOCKQUOTE","BODY","BR",
"CAPTION","CENTER","CITE","CODE",
"DD","DIR","DL","DT",
"EM","FONT","FORM","FRAME",
"FRAMESET","HEAD","HN","HR",
"HTML","I","IMG","INPUT",
"ISINDEX","KBD","LI","LINK",
"MAP","MENU","META","NOBR",
"NOFRAMES","OL","OPTION","P",
"PARAM","PRE","SAMP","SCRIPT",
"SELECT","SMALL","STRONG","SUB",
"SUP","TABLE","TD","TEXTAREA",
"TH","TITLE","TR","TT",
"U","UL","VAR","" };

typedef void (* pFuncRecord )(int fd, const char * url);

extern "C"{
void ShowStatus(int fd, const char * url);

};

static const pFuncRecord func_record[1]={
ShowStatus,// 1 

};

int DoHtmlFunction(int fd, const char *  url,unsigned short n)
{
if ((n>1 )|| (n<1)) return 0;
 (func_record[n-1])(fd,url);
return 1;
};

int DoHtmlVariable(int fd,WORD n) { return 0; };
